import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import { Toaster } from "sonner";
import "./globals.css";
import AuthWrapper from "./layouts/auth-layout";
import { QueryWrapper } from "./layouts/query.wrapper";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Workly Report App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${popins.className} antialiased bg-[#F9F9FB]`}>
        <NextTopLoader
          color="linear-gradient(to right, rgb(134, 239, 172), rgb(59, 130, 246), rgb(147, 51, 234))"
          speed={800}
          zIndex={9999}
        />
        <Suspense fallback={<div>Loading...</div>}>
          <QueryWrapper>
            <AuthWrapper>{children}</AuthWrapper>
          </QueryWrapper>
        </Suspense>
        <Toaster richColors />
      </body>
    </html>
  );
}
